### ISSUE TITLE
Add @flow to transpilers

### ISSUE THREAD

**Issue by kutyel** [Kikobeats/generator-git#84]
Would be nice to have **flow** other than just `coffee-script`.

I'll create a PR for this if you like the idea 😄

**Comment by Kikobeats** [comment]
Absolutely, just keep in mind that also is necessary add the way for "transpiling" flow using a command and add the packages necessaries 😄

**Comment by kutyel** [comment]
Sure! will do 😉

**Comment by kutyel** [comment]
This is just a reminder for myself, but using
```sh
npm install --save-dev flow-remove-types
```
there is no need to use Babel and it will work great with Node! ;)

**Comment by Kikobeats** [comment]
maybe @breadadams is interested in 😄

**Comment by breadadams** [comment]
We _had_ flow typing but you chose to remove it @kikobeats? 🤔
