### ISSUE TITLE
Favor Prettier instead of standard?

### ISSUE THREAD

**Issue by kutyel** [Kikobeats/generator-git#90]
I love standardjs but recently I am finding it quite annoying since I am using prettier with some rules similar to standard:
```sh
// .prettierrc
semi: false
singleQuote: true
trailingComma: es5
```
Should we remove the standard related config and just add some sane **prettier** defaults? 🤔

**Comment by Kikobeats** [comment]
standard → linter
prettier → formatter

Actually the project use both. If you want to customize your project, just add a config file.

**Comment by kutyel** [comment]
Yes, I know they have different responsibilities but right know when you format with prettier you still get linter errors from `standardjs`, which shouldn't be the case 😉

**Comment by Kikobeats** [comment]
I understood now what are you saying. For example prettier converts `function ()` into `function()`, then standard says that it needs to be `function ()`.

In my case my editor fix this on save. 

<img width="702" alt="screen shot 2017-12-20 at 11 25 04" src="https://user-images.githubusercontent.com/2096101/34202588-74d4c1c6-e578-11e7-8700-f63ab4bce1d0.png">

I prefer not to add an opinionated configuration file by default, although we are using opinionated things, we are doing the freedom to use what you want, so if you need something specific, you can create a configuration file.

**Comment by kutyel** [comment]
Yeah that's right, the main issue is the space before function parenthesis, which in @vscode is not working very nicely 😕

**Comment by Kikobeats** [comment]
haha, I supposed a problem related with editors; 

are you tried with vim?

**Comment by kutyel** [comment]
Nope, but you are still using Atom? 😜
